export const ARMY_RANKS = Object.freeze({
  COMMANDER: "COMMANDER",
  ARMY_COMMANDER: "ARMY_COMMANDER",
  DIVISION: "DIVISION",
  BRIGADE: "BRIGADE",
  REGIMENT: "REGIMENT",
  BATTALION: "BATTALION",
  COMPANY: "COMPANY",
  PLATOON: "PLATOON",
  ENGINEER: "ENGINEER",
  BOMB: "BOMB",
  MINE: "MINE",
  FLAG: "FLAG",
});

export const ARMY_RANK_LABELS = Object.freeze({
  COMMANDER: "司令",
  ARMY_COMMANDER: "军长",
  DIVISION: "师长",
  BRIGADE: "旅长",
  REGIMENT: "团长",
  BATTALION: "营长",
  COMPANY: "连长",
  PLATOON: "排长",
  ENGINEER: "工兵",
  BOMB: "炸弹",
  MINE: "地雷",
  FLAG: "军旗",
});

export const ARMY_RANK_STRENGTH = Object.freeze({
  COMMANDER: 9,
  ARMY_COMMANDER: 8,
  DIVISION: 7,
  BRIGADE: 6,
  REGIMENT: 5,
  BATTALION: 4,
  COMPANY: 3,
  PLATOON: 2,
  ENGINEER: 1,
});

export const ARMY_PIECE_SET = Object.freeze([
  ARMY_RANKS.COMMANDER,
  ARMY_RANKS.ARMY_COMMANDER,
  ARMY_RANKS.DIVISION, ARMY_RANKS.DIVISION,
  ARMY_RANKS.BRIGADE, ARMY_RANKS.BRIGADE,
  ARMY_RANKS.REGIMENT, ARMY_RANKS.REGIMENT,
  ARMY_RANKS.BATTALION, ARMY_RANKS.BATTALION,
  ARMY_RANKS.COMPANY, ARMY_RANKS.COMPANY, ARMY_RANKS.COMPANY,
  ARMY_RANKS.PLATOON, ARMY_RANKS.PLATOON, ARMY_RANKS.PLATOON,
  ARMY_RANKS.ENGINEER, ARMY_RANKS.ENGINEER, ARMY_RANKS.ENGINEER,
  ARMY_RANKS.BOMB, ARMY_RANKS.BOMB,
  ARMY_RANKS.MINE, ARMY_RANKS.MINE, ARMY_RANKS.MINE,
  ARMY_RANKS.FLAG,
]);
