// @ts-check

(function () {
  "use strict";

  const LEVEL_CAP = 20;

  /** @type {Record<string, number>} */
  const levelExperience = {
    1: 0,
    2: 60,
    3: 150,
    4: 280,
    5: 450,
    6: 680,
    7: 960,
    8: 1300,
    9: 1710,
    10: 2190,
    11: 2740,
    12: 3360,
    13: 4050,
    14: 4810,
    15: 5640,
    16: 6540,
    17: 7510,
    18: 8550,
    19: 9660,
    20: 10840,
  };

  const foods = [
    {
      id: "food.basic_grain",
      icon: "粮",
      name: "普通鼠粮",
      category: "food",
      price: 8,
      maxOwned: 99,
      hunger: 28,
      happiness: 2,
      health: 0,
      preference: "normal",
      description: "基础食品，便宜可靠。",
    },
    {
      id: "food.sunflower_seed",
      icon: "籽",
      name: "葵花籽",
      category: "food",
      price: 6,
      maxOwned: 99,
      hunger: 10,
      happiness: 9,
      health: 0,
      preference: "like",
      description: "团团最容易开心的小零食。",
    },
    {
      id: "food.corn",
      icon: "玉",
      name: "玉米粒",
      category: "food",
      price: 10,
      maxOwned: 99,
      hunger: 20,
      happiness: 3,
      health: 0,
      preference: "normal",
      description: "甜甜的常见食物。",
    },
    {
      id: "food.carrot",
      icon: "胡",
      name: "胡萝卜",
      category: "food",
      price: 12,
      maxOwned: 99,
      hunger: 18,
      happiness: 2,
      health: 4,
      preference: "normal",
      description: "清爽健康，状态低时很合适。",
    },
    {
      id: "food.apple",
      icon: "苹",
      name: "苹果片",
      category: "food",
      price: 12,
      maxOwned: 99,
      hunger: 12,
      happiness: 7,
      health: 1,
      preference: "like",
      description: "小口水果，快乐度小幅增加。",
    },
    {
      id: "food.cookie",
      icon: "饼",
      name: "小饼干",
      category: "food",
      price: 18,
      maxOwned: 99,
      hunger: 8,
      happiness: 14,
      health: 0,
      preference: "like",
      description: "奖励零食，别一次吃太多。",
    },
    {
      id: "food.nutri_bowl",
      icon: "餐",
      name: "营养餐",
      category: "food",
      price: 32,
      unlockLevel: 4,
      maxOwned: 50,
      hunger: 34,
      happiness: 8,
      health: 6,
      preference: "normal",
      description: "高级食品，综合恢复。",
    },
    {
      id: "food.water",
      icon: "水",
      name: "清水",
      category: "food",
      price: 4,
      maxOwned: 99,
      hunger: 4,
      happiness: 1,
      health: 2,
      preference: "normal",
      description: "基础饮品，少量恢复状态。",
    },
  ];

  const shopItems = [
    ...foods,
    {
      id: "care.bath_gel",
      icon: "泡",
      name: "基础浴液",
      category: "consumable",
      price: 10,
      maxOwned: 99,
      cleanliness: 32,
      description: "洗澡时使用，温和去尘。",
    },
    {
      id: "toy.ball",
      icon: "球",
      name: "基础小球",
      category: "toy",
      price: 20,
      maxOwned: 1,
      happiness: 12,
      energyCost: 9,
      description: "可以陪仓鼠玩滚球。",
    },
    {
      id: "toy.wheel",
      icon: "轮",
      name: "小跑轮",
      category: "toy",
      price: 45,
      unlockLevel: 2,
      maxOwned: 1,
      happiness: 16,
      energyCost: 12,
      description: "短跑几圈，精神一下。",
    },
    {
      id: "toy.box_maze",
      icon: "箱",
      name: "纸箱迷宫",
      category: "toy",
      price: 38,
      unlockLevel: 3,
      maxOwned: 1,
      happiness: 14,
      energyCost: 10,
      description: "适合钻来钻去的小游戏具。",
    },
    {
      id: "outfit.bowtie",
      icon: "领",
      name: "小领结",
      category: "outfit",
      price: 70,
      maxOwned: 1,
      description: "有礼貌的游戏厅伙伴。",
    },
    {
      id: "outfit.paper_hat",
      icon: "帽",
      name: "纸帽子",
      category: "outfit",
      price: 55,
      unlockLevel: 2,
      maxOwned: 1,
      description: "像刚从纸箱里探头。",
    },
    {
      id: "outfit.headset",
      icon: "耳",
      name: "游戏耳机",
      category: "outfit",
      price: 120,
      unlockLevel: 4,
      maxOwned: 1,
      description: "结算时特别有观战感。",
    },
    {
      id: "outfit.scarf",
      icon: "巾",
      name: "小围巾",
      category: "outfit",
      price: 95,
      unlockLevel: 5,
      maxOwned: 1,
      description: "适合晚风和散步。",
    },
    {
      id: "outfit.astronaut",
      icon: "宇",
      name: "宇航员头盔",
      category: "outfit",
      price: 220,
      unlockLevel: 8,
      maxOwned: 1,
      description: "太空射击纪念装扮。",
    },
    {
      id: "outfit.chef",
      icon: "厨",
      name: "厨师帽",
      category: "outfit",
      price: 140,
      unlockLevel: 6,
      maxOwned: 1,
      description: "打工归来很有成就感。",
    },
    {
      id: "outfit.sleep_cap",
      icon: "睡",
      name: "睡帽",
      category: "outfit",
      price: 90,
      unlockLevel: 3,
      maxOwned: 1,
      description: "睡觉动画的小小加成。",
    },
    {
      id: "furniture.comfy_bed",
      icon: "床",
      name: "软软小床",
      category: "furniture",
      price: 150,
      unlockLevel: 4,
      maxOwned: 1,
      sleepBoost: 1.08,
      description: "睡眠恢复略微提高。",
    },
    {
      id: "furniture.better_tub",
      icon: "盆",
      name: "云朵浴盆",
      category: "furniture",
      price: 130,
      unlockLevel: 4,
      maxOwned: 1,
      bathBoost: 1.08,
      description: "泡泡会多一点点。",
    },
    {
      id: "furniture.pixel_shelf",
      icon: "架",
      name: "收藏展示架",
      category: "furniture",
      price: 110,
      unlockLevel: 3,
      maxOwned: 1,
      description: "展示小游戏纪念物。",
    },
    {
      id: "room.arcade",
      icon: "厅",
      name: "极简游戏室",
      category: "room",
      price: 240,
      unlockLevel: 3,
      maxOwned: 1,
      description: "CREDIUS 风格的小小游戏房。",
    },
    {
      id: "room.forest",
      icon: "森",
      name: "森林木屋",
      category: "room",
      price: 320,
      unlockLevel: 6,
      maxOwned: 1,
      description: "木纹、叶影和轻松空气。",
    },
    {
      id: "room.starlight",
      icon: "星",
      name: "星空房间",
      category: "room",
      price: 460,
      unlockLevel: 10,
      maxOwned: 1,
      description: "适合露营归来的纪念背景。",
    },
    {
      id: "medicine.herb",
      icon: "草",
      name: "舒缓草药",
      category: "consumable",
      price: 24,
      maxOwned: 20,
      health: 16,
      description: "轻度不舒服时慢慢恢复。",
    },
  ];

  const studies = [
    {
      id: "study.math",
      skillId: "skill.math",
      title: "数学思维",
      icon: "数",
      unlockLevel: 2,
      durationMinutes: 10,
      energyCost: 8,
      hungerCost: 2,
      experience: 24,
      unlocksJobId: "job.cashier_math",
      description: "练习心算、找零和小小账本，学会后能做数字收银。",
    },
    {
      id: "study.arcade_tech",
      skillId: "skill.arcade_tech",
      title: "街机维护",
      icon: "机",
      unlockLevel: 4,
      durationMinutes: 25,
      energyCost: 14,
      hungerCost: 4,
      experience: 42,
      unlocksJobId: "job.arcade_technician",
      description: "认识按钮、线路和安全检修，解锁设备维护工作。",
    },
    {
      id: "study.route",
      skillId: "skill.route",
      title: "路线规划",
      icon: "路",
      unlockLevel: 6,
      durationMinutes: 40,
      energyCost: 20,
      hungerCost: 6,
      experience: 66,
      unlocksJobId: "job.route_planner",
      description: "学习地图和路线顺序，解锁更专业的物流安排。",
    },
    {
      id: "study.creative",
      skillId: "skill.creative",
      title: "创意设计",
      icon: "创",
      unlockLevel: 8,
      durationMinutes: 60,
      energyCost: 26,
      hungerCost: 8,
      experience: 96,
      unlocksJobId: "job.creative_planner",
      description: "练习配色、构图和灵感整理，解锁创意策划工作。",
    },
  ];

  const jobs = [
    {
      id: "job.store",
      title: "便利店理货",
      unlockLevel: 1,
      durationMinutes: 5,
      energyCost: 10,
      hungerCost: 4,
      cleanlinessCost: 3,
      baseCoins: 28,
      experience: 16,
      description: "把小货架摆整齐，快速稳定。",
    },
    {
      id: "job.cafe",
      title: "咖啡店助手",
      unlockLevel: 2,
      durationMinutes: 15,
      energyCost: 18,
      hungerCost: 6,
      cleanlinessCost: 5,
      baseCoins: 58,
      experience: 30,
      description: "帮忙递杯子，带回一点香气。",
    },
    {
      id: "job.arcade_shift",
      title: "游戏厅值班",
      unlockLevel: 3,
      durationMinutes: 30,
      energyCost: 26,
      hungerCost: 8,
      cleanlinessCost: 7,
      baseCoins: 96,
      experience: 48,
      description: "替 CREDIUS ARCADE 看一会儿灯。",
    },
    {
      id: "job.delivery",
      title: "快递小帮手",
      unlockLevel: 5,
      durationMinutes: 60,
      energyCost: 38,
      hungerCost: 12,
      cleanlinessCost: 11,
      baseCoins: 170,
      experience: 78,
      description: "背着小包跑一趟，收益更高。",
    },
    {
      id: "job.studio",
      title: "创意工作室",
      unlockLevel: 8,
      durationMinutes: 120,
      energyCost: 52,
      hungerCost: 16,
      cleanlinessCost: 12,
      baseCoins: 315,
      experience: 135,
      materialChance: 0.35,
      materialItemId: "material.ribbon",
      description: "帮忙整理灵感板，可能带回材料。",
    },
    {
      id: "job.night_guard",
      title: "夜间守护员",
      unlockLevel: 10,
      durationMinutes: 240,
      energyCost: 66,
      hungerCost: 20,
      cleanlinessCost: 16,
      baseCoins: 560,
      experience: 230,
      description: "慢慢值守，不要求半夜上线。",
    },
    {
      id: "job.cashier_math",
      title: "数字收银助理",
      unlockLevel: 3,
      requiredSkillId: "skill.math",
      durationMinutes: 45,
      energyCost: 28,
      hungerCost: 9,
      cleanlinessCost: 6,
      baseCoins: 132,
      experience: 64,
      description: "用数学课学到的心算整理账本和零钱。",
    },
    {
      id: "job.arcade_technician",
      title: "街机设备维护",
      unlockLevel: 5,
      requiredSkillId: "skill.arcade_tech",
      durationMinutes: 90,
      energyCost: 42,
      hungerCost: 13,
      cleanlinessCost: 14,
      baseCoins: 248,
      experience: 108,
      description: "检查按钮和线路，让游戏柜重新亮起来。",
    },
    {
      id: "job.route_planner",
      title: "路线规划员",
      unlockLevel: 7,
      requiredSkillId: "skill.route",
      durationMinutes: 150,
      energyCost: 50,
      hungerCost: 16,
      cleanlinessCost: 9,
      baseCoins: 390,
      experience: 162,
      description: "在地图上安排顺路的小任务，稳定完成长班次。",
    },
    {
      id: "job.creative_planner",
      title: "创意策划师",
      unlockLevel: 9,
      requiredSkillId: "skill.creative",
      durationMinutes: 240,
      energyCost: 62,
      hungerCost: 20,
      cleanlinessCost: 12,
      baseCoins: 610,
      experience: 246,
      materialChance: 0.45,
      materialItemId: "material.ribbon",
      description: "把灵感整理成新的游戏厅布置方案。",
    },
  ];

  const outings = [
    {
      id: "outing.park",
      title: "社区公园",
      unlockLevel: 1,
      durationMinutes: 5,
      energyCost: 8,
      hungerCost: 3,
      cleanlinessCost: 4,
      happiness: 15,
      affection: 4,
      experience: 14,
      collectibleChance: 0.35,
      collectibleItemId: "collectible.leaf",
      description: "跑一小圈，可能捡到叶子。",
    },
    {
      id: "outing.riverside",
      title: "河边散步",
      unlockLevel: 2,
      durationMinutes: 10,
      energyCost: 12,
      hungerCost: 4,
      cleanlinessCost: 5,
      happiness: 18,
      affection: 7,
      experience: 22,
      collectibleChance: 0.28,
      collectibleItemId: "collectible.pebble",
      description: "吹吹风，看水面闪光。",
    },
    {
      id: "outing.arcade",
      title: "游戏厅探险",
      unlockLevel: 3,
      durationMinutes: 15,
      energyCost: 16,
      hungerCost: 5,
      cleanlinessCost: 5,
      happiness: 22,
      affection: 8,
      experience: 32,
      collectibleChance: 0.24,
      collectibleItemId: "collectible.arcade_ticket",
      description: "看看闻风最近玩了什么。",
    },
    {
      id: "outing.funfair",
      title: "小型游乐园",
      unlockLevel: 6,
      durationMinutes: 25,
      energyCost: 28,
      hungerCost: 9,
      cleanlinessCost: 8,
      happiness: 34,
      affection: 12,
      experience: 52,
      collectibleChance: 0.2,
      collectibleItemId: "collectible.tiny_ticket",
      description: "快乐很多，也会有点累。",
    },
    {
      id: "outing.camping",
      title: "星空露营",
      unlockLevel: 10,
      durationMinutes: 30,
      energyCost: 34,
      hungerCost: 10,
      cleanlinessCost: 10,
      happiness: 42,
      affection: 18,
      experience: 76,
      collectibleChance: 0.45,
      collectibleItemId: "room.starlight",
      description: "带回一张很安静的夜空记忆。",
    },
  ];

  const themedMiniGameItems = {
    "2048": { itemId: "theme.2048_block", name: "数字方块玩具", icon: "2048" },
    tetris: { itemId: "theme.tetris_blocks", name: "彩色积木", icon: "TR" },
    "tank-battle": { itemId: "theme.tank_hat", name: "纸板坦克帽", icon: "TK" },
    snake: { itemId: "theme.snake_pillow", name: "蛇形抱枕", icon: "SN" },
    minesweeper: { itemId: "theme.flag_decor", name: "小旗子摆件", icon: "MN" },
    breakout: { itemId: "theme.paddle_toy", name: "像素挡板玩具", icon: "BK" },
    sudoku: { itemId: "theme.number_glasses", name: "数字眼镜", icon: "SD" },
    sokoban: { itemId: "theme.mini_box", name: "迷你纸箱", icon: "SB" },
    "space-shooter": { itemId: "theme.space_helmet", name: "宇航员头盔贴纸", icon: "SP" },
  };

  const balance = {
    version: 1,
    levelCap: LEVEL_CAP,
    levelExperience,
    starter: {
      coins: 80,
      hunger: 78,
      cleanliness: 76,
      energy: 78,
      happiness: 72,
      health: 96,
      affection: 8,
      inventory: [
        { itemId: "food.basic_grain", quantity: 5 },
        { itemId: "food.sunflower_seed", quantity: 6 },
        { itemId: "food.water", quantity: 4 },
        { itemId: "care.bath_gel", quantity: 2 },
        { itemId: "toy.ball", quantity: 1 },
        { itemId: "room.default", quantity: 1 },
      ],
    },
    offline: {
      maxHours: 36,
      hungerFloor: 10,
      cleanlinessFloor: 10,
      happinessFloor: 20,
      healthFloor: 55,
    },
    decayPerHour: {
      hunger: 1.25,
      cleanliness: 0.82,
      happiness: 0.42,
      healthStress: 0.12,
      workHunger: 0.25,
      workCleanliness: 0.22,
      outingHunger: 0.15,
      outingCleanliness: 0.28,
      sleepHunger: 0.42,
    },
    recoveryPerHour: {
      sleepEnergy: 24,
      sleepHealth: 2.4,
      restEnergy: 8,
      restHealth: 0.8,
    },
    action: {
      feedExperience: 8,
      feedAffection: 1,
      feedFullThreshold: 92,
      bathCleanEnoughThreshold: 88,
      bathCleanliness: 42,
      bathHappiness: 6,
      bathExperience: 10,
      bathAffection: 2,
      bathCooldownMinutes: 4,
      petCooldownMs: 90 * 1000,
      petHappiness: 5,
      petAffection: 2,
      petExperience: 4,
      playEnergyMinimum: 12,
      playEnergyCost: 10,
      playHappiness: 14,
      playAffection: 4,
      playExperience: 12,
      sleepHighEnergyThreshold: 84,
      sleepDurationMinutes: 180,
      workMinimumEnergy: 18,
      workMinimumHunger: 16,
      outingMinimumEnergy: 12,
      outingMinimumHunger: 12,
    },
    miniGame: {
      effectiveMinSeconds: 35,
      effectiveMinScore: 20,
      dailyNormalCap: 120,
      dailyExtraCap: 90,
      normalCoins: 8,
      normalExperience: 7,
      repeatCoins: 3,
      repeatExperience: 2,
      firstPlayCoins: 18,
      firstPlayExperience: 14,
      newRecordCoins: 22,
      newRecordExperience: 20,
    },
    dailyTaskReward: {
      coins: 18,
      experience: 14,
    },
    foods,
    shopItems,
    jobs,
    studies,
    outings,
    dailyTaskPool: [
      { id: "daily.feed", title: "喂食一次", type: "feed", target: 1 },
      { id: "daily.pet3", title: "抚摸仓鼠三次", type: "pet", target: 3 },
      { id: "daily.game", title: "完成一次小游戏", type: "miniGame", target: 1 },
      { id: "daily.work", title: "让仓鼠工作一次", type: "work", target: 1 },
      { id: "daily.play", title: "陪仓鼠玩一次", type: "play", target: 1 },
      { id: "daily.record", title: "刷新任意小游戏纪录", type: "record", target: 1 },
      { id: "daily.clean", title: "清洁仓鼠房间", type: "bath", target: 1 },
    ],
    achievements: [
      { id: "hamster.created", title: "新的伙伴", description: "创建仓鼠" },
      { id: "hamster.first_feed", title: "第一顿饭", description: "第一次喂食" },
      { id: "hamster.first_bath", title: "香喷喷", description: "第一次洗澡" },
      { id: "hamster.affection_60", title: "最佳拍档", description: "亲密度达到 60" },
      { id: "hamster.first_work", title: "打工鼠", description: "完成第一次工作" },
      { id: "hamster.coins_500", title: "小富鼠", description: "累计获得 500 仓鼠币" },
      { id: "hamster.games_5", title: "游戏搭档", description: "完成五款不同小游戏" },
      { id: "hamster.record", title: "纪录见证者", description: "见证任意小游戏新纪录" },
      { id: "hamster.all_outings", title: "环球小鼠", description: "解锁全部外出地点" },
      { id: "hamster.collector", title: "收藏家", description: "获得 8 件服饰或家具" },
      { id: "hamster.level_10", title: "长大啦", description: "达到 10 级" },
      { id: "hamster.level_20", title: "闻风之友", description: "达到 20 级" },
    ],
    themedMiniGameItems,
    bubbles: {
      morning: ["早呀，闻风。今天的街机厅也亮起来啦。", "团团把腮帮整理好了，准备营业。"],
      noon: ["午间巡逻完成，想吃一点小东西。", "游戏卡片看起来很香，不对，是很好玩。"],
      evening: ["晚上适合慢慢玩，也适合摸摸仓鼠。", "我在大厅等你回来。"],
      night: ["夜深啦，团团有点困，但还想陪你一会儿。", "小声一点，仓鼠屋准备关灯了。"],
      idle: ["今天也要一起玩！", "闻风回来啦！", "我把跑轮擦亮了。", "再摸一下嘛。"],
      hungry: ["肚子在小声咕咕。", "可以来一点鼠粮吗？"],
      dirty: ["毛毛有点乱，想洗个短短的澡。", "泡泡时间也不错。"],
      tired: ["跑轮先暂停一下，团团想趴会儿。", "精力条正在慢慢变软。"],
      happy: ["嘿嘿，好舒服。", "今天的状态不错哦。"],
      game: ["闻风，加油！", "再来一局一定能破纪录！", "我在大厅等你回来！"],
    },
  };

  globalThis.CrediusHamsterBalance = balance;
})();
