// @ts-check

(function () {
  "use strict";

  const levels = [
    {
      id: 1,
      name: "边境公路",
      zone: "灰岭防线",
      feature: "宽松整备 · 基础尸群",
      accent: "#efc669",
      roundSeconds: 48,
      bossSecond: 39,
      enemyGrace: 6,
      enemyDensity: 1,
      enemyHp: 1,
      enemySpeed: 1,
      lateWave: 0,
      bossHp: 170,
      rewardHp: 1,
      theme: {
        id: "border",
        weather: "none",
        skyTop: "#32443f",
        skyBottom: "#c2a66d",
        silhouette: "#293a35",
        ground: "#59614c",
        roadTop: "#626057",
        roadBottom: "#343a38",
        roadLine: "#e1d2a0",
        debris: "#8b6b48",
        barricade: "#765943",
        boss: "#536b4e",
      },
    },
    {
      id: 2,
      name: "冰封哨站",
      zone: "北境零号站",
      feature: "冻土视野 · 强化丧尸",
      accent: "#8ed8e6",
      roundSeconds: 48,
      bossSecond: 39,
      enemyGrace: 6,
      enemyDensity: 1.06,
      enemyHp: 1.08,
      enemySpeed: 1.03,
      lateWave: 0.08,
      bossHp: 205,
      rewardHp: 1.02,
      theme: {
        id: "frost",
        weather: "snow",
        skyTop: "#263943",
        skyBottom: "#9fb8ba",
        silhouette: "#304b52",
        ground: "#829596",
        roadTop: "#67777a",
        roadBottom: "#354348",
        roadLine: "#dce9e5",
        debris: "#587880",
        barricade: "#536b70",
        boss: "#507a78",
      },
    },
    {
      id: 3,
      name: "赤沙油田",
      zone: "红砾开采区",
      feature: "热浪扬尘 · 重尸增多",
      accent: "#63c7bd",
      roundSeconds: 48,
      bossSecond: 38.5,
      enemyGrace: 5.8,
      enemyDensity: 1.13,
      enemyHp: 1.16,
      enemySpeed: 1.06,
      lateWave: 0.16,
      bossHp: 245,
      rewardHp: 1.06,
      theme: {
        id: "oilfield",
        weather: "dust",
        skyTop: "#445756",
        skyBottom: "#d69558",
        silhouette: "#384842",
        ground: "#8b6748",
        roadTop: "#685b4c",
        roadBottom: "#343b38",
        roadLine: "#dcc378",
        debris: "#4c8580",
        barricade: "#5a5543",
        boss: "#6b7047",
      },
    },
    {
      id: 4,
      name: "暴雨港区",
      zone: "东岸集装码头",
      feature: "雨幕闪电 · 高密尸潮",
      accent: "#ef7770",
      roundSeconds: 48,
      bossSecond: 38,
      enemyGrace: 5.6,
      enemyDensity: 1.21,
      enemyHp: 1.24,
      enemySpeed: 1.1,
      lateWave: 0.24,
      bossHp: 290,
      rewardHp: 1.1,
      theme: {
        id: "harbor",
        weather: "rain",
        skyTop: "#172b34",
        skyBottom: "#526a70",
        silhouette: "#203740",
        ground: "#40585a",
        roadTop: "#41565b",
        roadBottom: "#1e2d32",
        roadLine: "#b9d0c9",
        debris: "#bb5f55",
        barricade: "#385b63",
        boss: "#4f6c64",
      },
    },
    {
      id: 5,
      name: "熔炉终局",
      zone: "黑钢核心区",
      feature: "余烬风暴 · 极限尸海",
      accent: "#ffb84f",
      roundSeconds: 48,
      bossSecond: 37.5,
      enemyGrace: 5.4,
      enemyDensity: 1.3,
      enemyHp: 1.34,
      enemySpeed: 1.14,
      lateWave: 0.34,
      bossHp: 345,
      rewardHp: 1.15,
      theme: {
        id: "furnace",
        weather: "embers",
        skyTop: "#211f25",
        skyBottom: "#8d5548",
        silhouette: "#2b2d2c",
        ground: "#4b443d",
        roadTop: "#4d4845",
        roadBottom: "#222726",
        roadLine: "#f0bd62",
        debris: "#a94f3f",
        barricade: "#454b47",
        boss: "#705c43",
      },
    },
  ];

  function getLevel(levelId) {
    const safeId = Math.min(levels.length, Math.max(1, Math.floor(Number(levelId) || 1)));
    return levels[safeId - 1];
  }

  globalThis.CrediusLastStandLevels = {
    TOTAL_LEVELS: levels.length,
    getLevel,
    levels,
  };
})();
